### ISSUE TITLE
Support changeName and changeDescription actions

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-product-type-import#11]
### Description
It looks like [here](https://github.com/sphereio/sphere-product-type-import/blob/master/src/product-type-import.js#L101) we do not support other actions than `addAttributeDefinition`.

**Comment by junajan** [comment]
Hello @wizzy25 .. please check this issue. If you find it not important please close it.

**Comment by wizzy25** [comment]
@junajan This involves adding new features, so personally I think it should be closed
